### ISSUE TITLE
Sell-to-cover shares should not be accounted for as a SELL event

### ISSUE THREAD

**Issue by deed02392** [mattjgalloway/cgtcalc#10]
I think this is not exactly an issue for this tool, because we can obviously work around it by simply not including the sell-to-cover shares, but it seems to be an interesting case where even HMRC are inconsistent in their messaging.

From https://web.archive.org/web/20220112102645/https://community.hmrc.gov.uk/customerforums/cgt/82d00dea-f06b-eb11-8fed-00155d975291 excerpted here for posterity:

> Hi HMRC,
> 
> I would like to query the correct way to calculate and report my capital gains resulting from Restricted Stock Units (RSUs) as provided as part of my compensation by my employer and the process that they follow to cover the income tax liability.
> 
> Example context using round numbers for simplicity:
> 
> Employee E is a UK tax resident and works for a company C which is headquartered in the US.
> 
> Company C provide employee E with an RSU grant of 400 shares with a vesting schedule of 100 shares per year for 4 years.
> 
> Company C operate a "sell to cover" (STC) scheme at vesting events to cover employee E's income tax liability resulting from the vested shares: when the 100 shares vest, they sell 45% and 2% of them to cover the income tax and NI contributions respectively. The value of the 100 shares is then included as income through PAYE and the proceeds from the automatic sale cover the additional tax and NI due. This results in a similar net pay to what employee E receives in other months.
> 
> After this STC, the remaining 53 shares are then available in employee E's trading account to keep, or sell at a later date.
> 
> The dates at which these events happen are ambiguous according to the available documentation from the trading account provider.
> 
> Firstly, the trading platform provides me with a "Confirmation of Release" document which specifies a "Release date" and details the shares vested and the shares sold to cover taxes and implies that everything happens on the same day.
> 
> However, in the trading platform, it turns out that the trade has actually happened the day after the "Release date", hereby refered to as the "Sell date". This is listed in a "Trade Confirmation" document.
> 
> Finally, the account statement for the month in which the vesting takes place, it specifies a "Receive date" which is one day after the "Sell date", and a "Settlement date" which is one day after the "Receive date".
> 
> For the simplicity of this example we assume that employee makes no additional trades (i.e. buying any more shares or manually selling any shares).
> 
> I have the following question which will inform how to acurrately calculate the capital gains liability for employee E:
> 
> Does HMRC consider employee E to have:
> 
>    a. Simply acquired 53 shares on the "receive date", meaning that the employee isn't considered to have disposed of any shares?
> 
>    b. Acquired 100 shares on the "Release date" and disposed of 47 shares on the same date, meaning that the disposal is matched with 47 of the 100 shares acquired on the same day using the "same day rule"? 
> 
>    c. Acquired 100 shares on the "Receive date" and disposed of 47 shares on the "Sell date", meaning that the disposal of 47 shares would be matched against 47 of the 100 acquired on the "Receive date" using the "bed and breakfast rule"?
> 
>    d. Acquired 100 shares on the "Release date" and disposed of 47 shares on the "Sell date", meaning that the 100 shares are added to the Section 104 holding, and that the disposal of 47 shares would be matched against the holding and the capital gain calculated using the average pool of cost of the holding?
> 
> As far as I can tell, (a) would be the simplest for reporting.
> 
> It could be argued that (b) might be more accurate and of the remaining options is most in keeping with the intention of the sell-to-cover process since employee E never had any agency over the 47 shares that were sold or, critically, WHEN they were sold.
> 
> If I understand correctly, (c) will be equivalent to (b) in the absense of any other trades, so this would ve fine too.
> 
> However, (d) would typically impose an unfair penalty on employee E that is not of their making. Consider the scenario where company C's share price has increased since previous vesting events. In this case the average pool of cost, after adding the 100 shares from this vesting event, would likely be significantly lower than the cost of the shares at the time of event. Therefore the capital gains will likely be significantly higher, through no fault of employee E. Specifically, if employee E had full agency over the 100 shares they could have sold them on the same day and avoided this issue.
> 
> Additionally, the company provide the following statement:
> 
> > After this tax withholding, [company C] transfers ownership of the remaining shares to you and deposits them in your [trading platform] account. You own these shares outright. 
> 
> This implies (a) but the income tax liability itself does not.

HMRC specifies both options a) or b) may apply, although one HMRC representative concedes option a) is the correct way.

**Comment by mattjgalloway** [comment]
Thanks for writing this @deed02392! This is helpful context for everyone to read.

Yes, this is not something the calculator needs to deal with specifically. You can account for any of these options (IIUC) in the calculator. e.g. for option a it's just not caring at all about the 47 shares that were sold to cover. And option b would be putting in a buy of 100 shares and sell of 47 shares at the market price the broker gives.

I would note that same day or B&B rules work here to make it so that, IIUC, options A, B and C all effectively net out to the same thing. I can't see how you'd say the acquisition price or disposal price would be different because of changing the day (except for I guess currency exchange rates if you wanted to account for the difference on the different dates). Option D would be different though.
